language: r
warnings_are_errors: true

cache: packages

sudo: required

r_github_packages:
  - jimhester/covr@shiny-app
  - jimhester/shinytest@covr
  - frehbach/EventDetectGUI

after_success:
  - R -f run_tests.R
  - Rscript -e 'library(covr);codecov()'
