language: r
warnings_are_errors: true

cache: packages

sudo: required

r_github_packages:
  - jimhester/covr
  - jimhester/shinytest
  - frehbach/EventDetectGUI

after_success:
  - Rscript -e 'library(covr);codecov()'
